name: "Multi Event Workflow"

on:
    push:
        branches:
            - main
            - dev
            
    pull_request:
        branches:
            - main
            - dev

jobs:
    hello_world:
        runs-on: ubuntu-latest
        steps:
            - run: "echo \"REF: $GITHUB_REF\""
            - run: "echo \"SHA: $GITHUB_SHA\""
            - run: "echo \"ACTOR: $GITHUB_ACTOR\""
            - run: "echo \"Action: $GITHUB_ACTION\""
            - run: "echo \"JOB: $GITHUB_JOB\""